### ISSUE TITLE
sensio Workaround

### ISSUE THREAD

**Issue by designpilot** [cgoIT/contao-rate-it-bundle#5]
Damit man die RateIt Erweiterung installieren kann, geht man wie folgt vor.

die composer.json erweitern mit:
"sensio/framework-extra-bundle": "^5.2.2"

Danach geht man in den Contao Manager und klickt auf "Pakete aktualisieren" jetzt kann man entsprechend die RateIt Erweiterung installieren.

Ich hab das ganze rudimentär getestet, also eine blanke Installation ohne Theme, Layout usw. (einmal habe ich es einfach als Inhaltselement angelegt und einmal direkt in der Seite aktiviert) Wenn man nun im BE links oben auf Rateit klickt wird man sehen das es dort bereits 2 Einträge generiert hat.

Getestet habe ich das auf einer Contao 4.6.x Installation also sollte es auf der 4.4.28 sowieso laufen.

**Comment by w3scout** [comment]
eben erfolgreich unter 4.4.29 getestet.

**Comment by designpilot** [comment]
In der Zwischenzeit erübrigt sich das manuelle hinzufügen von sensio/frameworl-extra-bundle weil es bei einem Update (aktualisieren der Pakete) im Contao Manager aktualisiert wird.
